SHELL = /bin/bash

all: exercicios.c

#	@git add exercicios.c > /dev/null
#	@git commit -m "Tentativa de resolução: lab 7." > /dev/null
	gcc -Wall -Og -std=c99 exercicios.c -o exercicios;\
	./exercicios; exit "$$?"
